baseURL = "https://subroy13.github.io"
languageCode = "en-us"
title = "Subhrajyoty Roy"
paginate = 10
disqusShortname = "subroy13"
publishDir = "docs"


[markup.goldmark.renderer]
  unsafe= true

[taxonomies]
  tag = "tags"



